{
  inputs,
  lib,
  config,
  pkgs,
  ...
}: let
  cfg = config.dotfiles.programs.neovim;
  stylixCfg = config.theme;
  themes = import "${inputs.dotstylix}/themes" {inherit lib;};
  paletteAttrset = themes.${stylixCfg.scheme};
  paletteToLua = attrs:
    lib.concatStringsSep "\n" (
      lib.mapAttrsToList (name: value: "          ${name} = \"#${value}\",") attrs
    );
  colorschemeLua = ''
    --
    -- THIS FILE IS DYNAMICALLY GENERATED BY NIX
    --
    return {
      {
        "nvim-mini/mini.nvim",
        priority = 1000,
        config = function()
          require("mini.base16").setup({
            palette = {
              ${paletteToLua paletteAttrset}
            },
            use_cterm = false,
            plugins = { default = true }

          })

          local transparent_groups = {
            "Normal",
            "NormalNC",
            "SignColumn",
            "LineNr",
            "LineNrAbove",
            "LineNrBelow",
            "CursorLineNr",
            "FoldColumn",
            "EndOfBuffer",
            "StatusLine",
            "StatusLineNC",
            "GitSignsAdd",
            "GitSignsChange",
            "GitSignsDelete",
            "GitSignsUntracked",
            "DiagnosticSignError",
            "DiagnosticSignWarn",
            "DiagnosticSignInfo",
            "DiagnosticSignHint",
            "DiagnosticSignOk",
          }

          for _, group in ipairs(transparent_groups) do
            vim.cmd(("highlight %s guibg=NONE ctermbg=NONE"):format(group))
          end

          vim.api.nvim_set_hl(0, "PmenuSel", {
            fg = "#${paletteAttrset.base05}",
            bg = "#${paletteAttrset.base02}",
            bold = true,
          })
        end,
      },
    }
  '';
in {
  options.dotfiles.programs.neovim = {
    enable = lib.mkEnableOption "Enable the neovim feature";
    discordPresence = lib.mkEnableOption "opt-in Discord rich presence for Neovim";
  };

  config = lib.mkIf cfg.enable {
    programs.neovim = {
      enable = true;
      defaultEditor = true;
      viAlias = true;
      vimAlias = true;
      vimdiffAlias = true;
      plugins = [pkgs.vimPlugins.lazy-nvim];
      extraPackages = with pkgs; [
        gcc
        xclip
        xsel
        wl-clipboard
        ripgrep
        fd
        trash-cli
        imagemagick
        ghostscript
        mermaid-cli
        alejandra
        black
        google-java-format
        stylua
        prettier
        checkstyle
        eslint_d
        ktlint
        luajitPackages.luacheck
        ruff
        shellcheck
        statix
        tree-sitter
        lua-language-server
        pyright
        rust-analyzer
        rustfmt
        typescript-language-server
        jdt-language-server
        nixd
        clang-tools
        vscode-extensions.vadimcn.vscode-lldb.adapter
        gopls
        marksman
      ];
      withRuby = false;
      withPython3 = false;
    };

    home.sessionVariables = lib.mkIf cfg.discordPresence {
      NVIM_ENABLE_CORD = "1";
    };

    xdg.configFile."nvim" = {
      recursive = true;
      source = inputs.dotnvim;
    };

    xdg.configFile."nvim/lua/plugins/colorscheme.lua" = lib.mkIf stylixCfg.enable {
      text = colorschemeLua;
      onChange = ''
        rm -rf "${config.xdg.cacheHome}/nvim/"

      '';
    };

    xdg.configFile."clangd/config.yaml".text = ''
      Completion:
        HeaderInsertion: Never
      Diagnostics:
        MissingIncludes: None
        Includes:
          IgnoreHeader: 'vulkan_core\.h$'
    '';
  };
}
