repos:
  - repo: local
    hooks:
      - id: alejandra
        name: alejandra
        entry: alejandra
        language: system
        files: \.nix$
      - id: shellcheck
        name: shellcheck
        entry: shellcheck
        language: system
        files: \.sh$
      - id: deadnix
        name: deadnix
        entry: deadnix --fail
        language: system
        files: \.nix$
