repos:
  - repo: local
    hooks:
      - id: alejandra
        name: alejandra
        entry: alejandra
        language: system
        files: \.nix$
      - id: re-add-fixes
        name: re-add fixed files
        entry: git add .
        language: system
        always_run: true
        pass_filenames: false
