return {
  "startup-nvim/startup.nvim",
  dependencies = { "nvim-telescope/telescope.nvim", "nvim-lua/plenary.nvim"},
  config = function()
    require("startup").setup({
      header = {
        type = "text",
        align = "center",
        fold_section = false,
        title = "Header",
        margin = 5,
        content = {
          [[╔────────────────────────────────────────────────────────────────────╗]],
          [[│                                                                    │]],
          [[│  ███▄ ▄███▓ ▄▄▄      ▓█████▄ ▓█████  ██▓     ██▓ ███▄    █ ▓█████  │]],
          [[│ ▓██▒▀█▀ ██▒▒████▄    ▒██▀ ██▌▓█   ▀ ▓██▒    ▓██▒ ██ ▀█   █ ▓█   ▀  │]],
          [[│ ▓██    ▓██░▒██  ▀█▄  ░██   █▌▒███   ▒██░    ▒██▒▓██  ▀█ ██▒▒███    │]],
          [[│ ▒██    ▒██ ░██▄▄▄▄██ ░▓█▄   ▌▒▓█  ▄ ▒██░    ░██░▓██▒  ▐▌██▒▒▓█  ▄  │]],
          [[│ ▒██▒   ░██▒ ▓█   ▓██▒░▒████▓ ░▒████▒░██████▒░██░▒██░   ▓██░░▒████▒ │]],
          [[│ ░ ▒░   ░  ░ ▒▒   ▓▒█░ ▒▒▓  ▒ ░░ ▒░ ░░ ▒░▓  ░░▓  ░ ▒░   ▒ ▒ ░░ ▒░ ░ │]],
          [[│ ░  ░      ░  ▒   ▒▒ ░ ░ ▒  ▒  ░ ░  ░░ ░ ▒  ░ ▒ ░░ ░░   ░ ▒░ ░ ░  ░ │]],
          [[│ ░      ░     ░   ▒    ░ ░  ░    ░     ░ ░    ▒ ░   ░   ░ ░    ░    │]],
          [[│        ░         ░  ░   ░       ░  ░    ░  ░ ░           ░    ░  ░ │]],
          [[│                       ░                                            │]],
          [[│                                                                    │]],
          [[╚────────────────────────────────────────────────────────────────────╝]],
        },
        highlight = "Statement",
        default_color = "",
        oldfiles_amount = 0,
      },
      body = {
        type = "mapping",
        oldfiles_directory = false,
        align = "center",
        fold_section = false,
        title = "Basic Commands",
        margin = 1,
        content = {
          { " Find File", "Telescope find_files", "<leader>ff" },
          { "󰍉 Find Word", "Telescope live_grep", "<leader>lg" },
          { " Recent Files", "Telescope oldfiles", "<leader>of" },
          { " New File", "lua require'startup'.new_file()", "<leader>nf" },
          { "󰩈 Exit", "q", "<leader>q" },
        },
        highlight = "String",
        default_color = "",
        oldfiles_amount = 0,
      },
      body2 = {
        type = "oldfiles",
        oldfiles_directory = true,
        align = "center",
        fold_section = true,
        title = "Recent Files",
        margin = 5,
        content = {
        },
        highlight = "TSString",
        default_color = "#FFFFFF",
        oldfiles_amount = 5,
      },
      footer = {
        type = "text",
        oldfiles_directory = false,
        align = "center",
        fold_section = false,
        title = "Footer",
        margin = 5,
        content = { "baho mo." },
        highlight = "Number",
        default_color = "",
        oldfiles_amount = 0,
      },

      options = {
        mapping_keys = true,
        cursor_column = 0.5,
        empty_lines_between_mappings = true,
        disable_statuslines = true,
        paddings = { 1, 2, 3, 4 },
      },
      mappings = {
        execute_command = "<CR>",
        open_file = "o",
        open_file_split = "<c-o>",
        open_section = "<TAB>",
        open_help = "?",
      },
      colors = {
        background = "#1f2227",
        folded_section = "#56b6c2",
      },
      parts = { "header", "body", "body2", "footer" },
    })
  end
}
